### ISSUE TITLE
Allow to select installation path

### ISSUE THREAD

**Issue by piggylux** [CollinMcKinney/LeagueLocaleLauncher#1]
Currently it tries to patch config in `C:\Riot Games\League of Legends\Config\LeagueClientSettings.yaml` only.

https://github.com/CollinMcKinney-jabukufo/LeagueLocaleLauncher/blob/6cd6bf8635249ba39a0226d1fffec447f6ccb4bf/LeagueLocaleLauncher/Config.cs#L16

**Comment by CollinMcKinney** [comment]
You can change the settings path in the tool's "config.yaml" file.
