### ISSUE TITLE
It will not open my league client.

### ISSUE THREAD

**Issue by iSettheTone** [CollinMcKinney/LeagueLocaleLauncher#3]
Hello I recently downloaded the new version from here since it wasn't working since the new update. It loads up and lets me choose the location and language but it can not open the league client. I see in my task manager that it tries to load it but then the league client quickly closes afterwards. I checked the config.yaml file and everything is correct. Is anyone else having this issue or is there any fix to it?

**Comment by iSettheTone** [comment]
Some more information that might help you. The LeagueLocale program closes 99% of the time after I choose my language and server. League of Legends never opens but in my task manager it shows it for a few seconds then it disappears but I do have the "RiotClientCrashHandler" and "RiotClientServices" in my Task Manager that stays there until I manually end the tasks. I cant even open League of Legends regularly without ending those tasks first manually.

**Comment by iSettheTone** [comment]
Also I just opened League of Legends manually after it kept failing to load LAN in English with the LeagueLocale program and it somehow is in English without being opened with the LeagueLocale program.

**Comment by CollinMcKinney** [comment]
I just created a discord server, if you come there for additional help I will generally get back to you faster https://discord.gg/vA4w7rn

The way Riot has their client set up, it needs to be launched & closed for the language/region to be changed consistently. So to play with the changed language/region you actually have to launch the client a second time after closing it. This launcher is programmed to manage that on it's own by changing the settings, launching, closing, and then launching again. If you wait does the client eventually open? I'm thinking maybe what you're seeing could be the first launch/close. It shouldn't take much longer than launching using the official LoL shortcut. I have a pretty old machine and it usually finishes launching within a minute.

In regards to your last comment, the "launcher" works by changing the language in the game files, and then launching the game. So actually after you launch with it once you don't really need to use it anymore unless you need to change region/languages again. So this behavior is expected.

**Comment by iSettheTone** [comment]
Windows 10 and yes I even tried running as administrator. I have restarted my computer since then and I opened the client normally and logged on LAN today and it was in English even without your program. I’m not sure whats going on but its like changed my client to have English even in LAN now without me using your program. I’m not upset about it though. Haha  Sent from Mail for Windows 10 From: jabukufoSent: Friday, May 22, 2020 12:08 AMTo: CollinMcKinney-jabukufo/LeagueLocaleLauncherCc: iSettheTone; AuthorSubject: Re: [CollinMcKinney-jabukufo/LeagueLocaleLauncher] It will not open my league client. (#3) What OS are you using?Do the file paths in "config.yaml" both lead to existing files?Have you tried running the launcher as Administrator?In regards to your last comment, the "launcher" works by changing the language in the files, and then launching the game. So actually after you launch with it once you don't really need to use it anymore unless you need to change region/languages again. So this behavior is expected.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by iSettheTone** [comment]
Ok the launcher opens and closes the client but does not reopen it the second time. I have to manually open the client but the language is changed. I have windows 10. Could you maybe put that information in the readme? The last time I used the program it was different and just opened the client regularly on the first try so I thought it was not working properly. I have a very expensive nice computer so I dont think it it is just being impatient. The launcher just is not opening the client the second time. I have to manually open it but the language and everything is changed to English like I want on LAN servers. Thank you for your replies. This is a free program you made for the community. I and I am sure many others greatly appreciate your work. Do not feel bad for taking time to reply. You do not get paid for this. This program is charity work and greatly appreciate that. I think the problem is that the client cant reopen because yes it closes the League Client but not the  RiotClientServices or  RiotClientCrashHandler and without closing those first the client can not reopen. After I use your program to change the language I have to manually close those with task manager to open it manually. I think that is the source of the problem.

**Comment by CollinMcKinney** [comment]
I just put out an updated release that I believe should fix this issue. Please let me know if it works or not.

**Comment by iSettheTone** [comment]
Sorry I have been busy but it works exactly as you intended now. It opens the client without problems. Thank you for addressing and fixing this issue and also making a great free program!
