### ISSUE TITLE
LLL 1.2.2 fails to save folder location.

### ISSUE THREAD

**Issue by Oblituarius** [CollinMcKinney/LeagueLocaleLauncher#8]
Just updated from 1.1.1 to 1.2.2. LLL fails to save the custom League folder location and it asks for it every time you want to use it.
Setting config.yaml to Read-Only will make LLL unable to launch at all.
Going back to 1.1.1 in the mean time.

**Comment by ownchoice** [comment]
Having the same problem since 1.2, pretty annoying.
